apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: db2
  name: db2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: db2
    spec:
      containers:
      - image: redis:latest
        name: db2
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
status: {}
