apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: rest2
  name: rest2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rest2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: rest2
    spec:
      containers:
      - image: milovanovicsnikola/s3:v2
        name: rest2
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
