version: '3.3'

services:
    broker:
     image: rabbitmq:latest
     ports:
       - "5672:5672"
    db1:
     depends_on:
      - broker
     image: redis:latest
     ports:
       - "6379:6379"
    db2:
     depends_on:
      - broker
     image: redis:latest
     ports:
       - "6380:6379"
    rest1:
     depends_on:
      - db1
     image: service1
     ports:
       - "8080:8080"
     network_mode: "host"
    rest2:
     depends_on:
       - db2
     image: service2
     ports:
       - "8081:8081"
     network_mode: "host"
